Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import dora; dora.start_runtime() # hand_rec
                 ~~~~~~~~~~~~~~~~~~^^
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator hand_rec/op raised an error
   2: error in Python module at /Users/dave/dev/ultra/dora_webcam/hand_rec.py
   3: Traceback (most recent call last):
        File "/Users/dave/dev/ultra/dora_webcam/hand_rec.py", line 76, in on_event
          image = torch.tensor(value.copy(), dtype=torch.uint8).to(self.device)

      AttributeError: 'pyarrow.lib.UInt8Array' object has no attribute 'copy'

Location:
    binaries/runtime/src/operator/python.rs:29:9
