Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import dora; dora.start_runtime() # plot
                 ~~~~~~~~~~~~~~~~~~^^
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator plot/op raised an error
   2: error in Python module at /Users/dave/dev/ultra/dora_webcam/plot.py
   3: Traceback (most recent call last):
        File "/Users/dave/dev/ultra/dora_webcam/plot.py", line 53, in on_event
          draw_landmarks(image, landmarks[:,:2], HAND_CONNECTIONS, size=2)

      TypeError: list indices must be integers or slices, not tuple

Location:
    binaries/runtime/src/operator/python.rs:29:9
